/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CCommunityIdRouteImport } from './routes/c.$communityId'
import { Route as CCommunityIdIndexRouteImport } from './routes/c.$communityId.index'
import { Route as CCommunityIdInboxRouteImport } from './routes/c.$communityId.inbox'
import { Route as CCommunityIdMemoryRouteImport } from './routes/c.$communityId.memory'
import { Route as CCommunityIdSettingsRouteImport } from './routes/c.$communityId.settings'
import { Route as CCommunityIdAgentsIndexRouteImport } from './routes/c.$communityId.agents.index'
import { Route as CCommunityIdAgentsAgentIdRouteImport } from './routes/c.$communityId.agents.$agentId'
import { Route as CCommunityIdChannelsChannelIdRouteImport } from './routes/c.$communityId.channels.$channelId'
import { Route as CCommunityIdMessagesNewRouteImport } from './routes/c.$communityId.messages.new'
import { Route as CCommunityIdChannelsChannelIdThreadsThreadIdRouteImport } from './routes/c.$communityId.channels.$channelId.threads.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CCommunityIdRoute = CCommunityIdRouteImport.update({
  id: '/c/$communityId',
  path: '/c/$communityId',
  getParentRoute: () => rootRouteImport,
} as any)
const CCommunityIdIndexRoute = CCommunityIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CCommunityIdRoute,
} as any)
const CCommunityIdInboxRoute = CCommunityIdInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => CCommunityIdRoute,
} as any)
const CCommunityIdMemoryRoute = CCommunityIdMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => CCommunityIdRoute,
} as any)
const CCommunityIdSettingsRoute = CCommunityIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CCommunityIdRoute,
} as any)
const CCommunityIdAgentsIndexRoute = CCommunityIdAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => CCommunityIdRoute,
} as any)
const CCommunityIdAgentsAgentIdRoute =
  CCommunityIdAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => CCommunityIdRoute,
  } as any)
const CCommunityIdChannelsChannelIdRoute =
  CCommunityIdChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => CCommunityIdRoute,
  } as any)
const CCommunityIdMessagesNewRoute = CCommunityIdMessagesNewRouteImport.update({
  id: '/messages/new',
  path: '/messages/new',
  getParentRoute: () => CCommunityIdRoute,
} as any)
const CCommunityIdChannelsChannelIdThreadsThreadIdRoute =
  CCommunityIdChannelsChannelIdThreadsThreadIdRouteImport.update({
    id: '/threads/$threadId',
    path: '/threads/$threadId',
    getParentRoute: () => CCommunityIdChannelsChannelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/c/$communityId': typeof CCommunityIdRouteWithChildren
  '/c/$communityId/inbox': typeof CCommunityIdInboxRoute
  '/c/$communityId/memory': typeof CCommunityIdMemoryRoute
  '/c/$communityId/settings': typeof CCommunityIdSettingsRoute
  '/c/$communityId/': typeof CCommunityIdIndexRoute
  '/c/$communityId/agents/$agentId': typeof CCommunityIdAgentsAgentIdRoute
  '/c/$communityId/channels/$channelId': typeof CCommunityIdChannelsChannelIdRouteWithChildren
  '/c/$communityId/messages/new': typeof CCommunityIdMessagesNewRoute
  '/c/$communityId/agents/': typeof CCommunityIdAgentsIndexRoute
  '/c/$communityId/channels/$channelId/threads/$threadId': typeof CCommunityIdChannelsChannelIdThreadsThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/c/$communityId/inbox': typeof CCommunityIdInboxRoute
  '/c/$communityId/memory': typeof CCommunityIdMemoryRoute
  '/c/$communityId/settings': typeof CCommunityIdSettingsRoute
  '/c/$communityId': typeof CCommunityIdIndexRoute
  '/c/$communityId/agents/$agentId': typeof CCommunityIdAgentsAgentIdRoute
  '/c/$communityId/channels/$channelId': typeof CCommunityIdChannelsChannelIdRouteWithChildren
  '/c/$communityId/messages/new': typeof CCommunityIdMessagesNewRoute
  '/c/$communityId/agents': typeof CCommunityIdAgentsIndexRoute
  '/c/$communityId/channels/$channelId/threads/$threadId': typeof CCommunityIdChannelsChannelIdThreadsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/c/$communityId': typeof CCommunityIdRouteWithChildren
  '/c/$communityId/inbox': typeof CCommunityIdInboxRoute
  '/c/$communityId/memory': typeof CCommunityIdMemoryRoute
  '/c/$communityId/settings': typeof CCommunityIdSettingsRoute
  '/c/$communityId/': typeof CCommunityIdIndexRoute
  '/c/$communityId/agents/$agentId': typeof CCommunityIdAgentsAgentIdRoute
  '/c/$communityId/channels/$channelId': typeof CCommunityIdChannelsChannelIdRouteWithChildren
  '/c/$communityId/messages/new': typeof CCommunityIdMessagesNewRoute
  '/c/$communityId/agents/': typeof CCommunityIdAgentsIndexRoute
  '/c/$communityId/channels/$channelId/threads/$threadId': typeof CCommunityIdChannelsChannelIdThreadsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/settings'
    | '/c/$communityId'
    | '/c/$communityId/inbox'
    | '/c/$communityId/memory'
    | '/c/$communityId/settings'
    | '/c/$communityId/'
    | '/c/$communityId/agents/$agentId'
    | '/c/$communityId/channels/$channelId'
    | '/c/$communityId/messages/new'
    | '/c/$communityId/agents/'
    | '/c/$communityId/channels/$channelId/threads/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/settings'
    | '/c/$communityId/inbox'
    | '/c/$communityId/memory'
    | '/c/$communityId/settings'
    | '/c/$communityId'
    | '/c/$communityId/agents/$agentId'
    | '/c/$communityId/channels/$channelId'
    | '/c/$communityId/messages/new'
    | '/c/$communityId/agents'
    | '/c/$communityId/channels/$channelId/threads/$threadId'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/settings'
    | '/c/$communityId'
    | '/c/$communityId/inbox'
    | '/c/$communityId/memory'
    | '/c/$communityId/settings'
    | '/c/$communityId/'
    | '/c/$communityId/agents/$agentId'
    | '/c/$communityId/channels/$channelId'
    | '/c/$communityId/messages/new'
    | '/c/$communityId/agents/'
    | '/c/$communityId/channels/$channelId/threads/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  SettingsRoute: typeof SettingsRoute
  CCommunityIdRoute: typeof CCommunityIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$communityId': {
      id: '/c/$communityId'
      path: '/c/$communityId'
      fullPath: '/c/$communityId'
      preLoaderRoute: typeof CCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$communityId/': {
      id: '/c/$communityId/'
      path: '/'
      fullPath: '/c/$communityId/'
      preLoaderRoute: typeof CCommunityIdIndexRouteImport
      parentRoute: typeof CCommunityIdRoute
    }
    '/c/$communityId/inbox': {
      id: '/c/$communityId/inbox'
      path: '/inbox'
      fullPath: '/c/$communityId/inbox'
      preLoaderRoute: typeof CCommunityIdInboxRouteImport
      parentRoute: typeof CCommunityIdRoute
    }
    '/c/$communityId/memory': {
      id: '/c/$communityId/memory'
      path: '/memory'
      fullPath: '/c/$communityId/memory'
      preLoaderRoute: typeof CCommunityIdMemoryRouteImport
      parentRoute: typeof CCommunityIdRoute
    }
    '/c/$communityId/settings': {
      id: '/c/$communityId/settings'
      path: '/settings'
      fullPath: '/c/$communityId/settings'
      preLoaderRoute: typeof CCommunityIdSettingsRouteImport
      parentRoute: typeof CCommunityIdRoute
    }
    '/c/$communityId/agents/': {
      id: '/c/$communityId/agents/'
      path: '/agents'
      fullPath: '/c/$communityId/agents/'
      preLoaderRoute: typeof CCommunityIdAgentsIndexRouteImport
      parentRoute: typeof CCommunityIdRoute
    }
    '/c/$communityId/agents/$agentId': {
      id: '/c/$communityId/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/c/$communityId/agents/$agentId'
      preLoaderRoute: typeof CCommunityIdAgentsAgentIdRouteImport
      parentRoute: typeof CCommunityIdRoute
    }
    '/c/$communityId/channels/$channelId': {
      id: '/c/$communityId/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/c/$communityId/channels/$channelId'
      preLoaderRoute: typeof CCommunityIdChannelsChannelIdRouteImport
      parentRoute: typeof CCommunityIdRoute
    }
    '/c/$communityId/messages/new': {
      id: '/c/$communityId/messages/new'
      path: '/messages/new'
      fullPath: '/c/$communityId/messages/new'
      preLoaderRoute: typeof CCommunityIdMessagesNewRouteImport
      parentRoute: typeof CCommunityIdRoute
    }
    '/c/$communityId/channels/$channelId/threads/$threadId': {
      id: '/c/$communityId/channels/$channelId/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/c/$communityId/channels/$channelId/threads/$threadId'
      preLoaderRoute: typeof CCommunityIdChannelsChannelIdThreadsThreadIdRouteImport
      parentRoute: typeof CCommunityIdChannelsChannelIdRoute
    }
  }
}

interface CCommunityIdChannelsChannelIdRouteChildren {
  CCommunityIdChannelsChannelIdThreadsThreadIdRoute: typeof CCommunityIdChannelsChannelIdThreadsThreadIdRoute
}

const CCommunityIdChannelsChannelIdRouteChildren: CCommunityIdChannelsChannelIdRouteChildren =
  {
    CCommunityIdChannelsChannelIdThreadsThreadIdRoute:
      CCommunityIdChannelsChannelIdThreadsThreadIdRoute,
  }

const CCommunityIdChannelsChannelIdRouteWithChildren =
  CCommunityIdChannelsChannelIdRoute._addFileChildren(
    CCommunityIdChannelsChannelIdRouteChildren,
  )

interface CCommunityIdRouteChildren {
  CCommunityIdInboxRoute: typeof CCommunityIdInboxRoute
  CCommunityIdMemoryRoute: typeof CCommunityIdMemoryRoute
  CCommunityIdSettingsRoute: typeof CCommunityIdSettingsRoute
  CCommunityIdIndexRoute: typeof CCommunityIdIndexRoute
  CCommunityIdAgentsAgentIdRoute: typeof CCommunityIdAgentsAgentIdRoute
  CCommunityIdChannelsChannelIdRoute: typeof CCommunityIdChannelsChannelIdRouteWithChildren
  CCommunityIdMessagesNewRoute: typeof CCommunityIdMessagesNewRoute
  CCommunityIdAgentsIndexRoute: typeof CCommunityIdAgentsIndexRoute
}

const CCommunityIdRouteChildren: CCommunityIdRouteChildren = {
  CCommunityIdInboxRoute: CCommunityIdInboxRoute,
  CCommunityIdMemoryRoute: CCommunityIdMemoryRoute,
  CCommunityIdSettingsRoute: CCommunityIdSettingsRoute,
  CCommunityIdIndexRoute: CCommunityIdIndexRoute,
  CCommunityIdAgentsAgentIdRoute: CCommunityIdAgentsAgentIdRoute,
  CCommunityIdChannelsChannelIdRoute:
    CCommunityIdChannelsChannelIdRouteWithChildren,
  CCommunityIdMessagesNewRoute: CCommunityIdMessagesNewRoute,
  CCommunityIdAgentsIndexRoute: CCommunityIdAgentsIndexRoute,
}

const CCommunityIdRouteWithChildren = CCommunityIdRoute._addFileChildren(
  CCommunityIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  SettingsRoute: SettingsRoute,
  CCommunityIdRoute: CCommunityIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
